config/routes.rb
MusicApp::Application.routes.draw do
  resources :bands
  resources :notes, :only => [:create, :destroy]
  resources :users, :only => [:create, :destroy]
  resource :session

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'activate', to: 'users#activate'

  resources :albums do
    resources :tracks, :except => [:index]
  end

  resource :session, :only => [:create, :new, :destroy]
end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :band_id, :title

  belongs_to :band,
    :class_name => "Band",
    :primary_key => :id,
    :foreign_key => :band_id

  has_many :tracks,
    :class_name => "Track",
    :primary_key => :id,
    :foreign_key => :album_id,
    :dependent => :destroy
end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :name

  has_many :albums,
    :class_name => "Album",
    :primary_key => :id,
    :foreign_key => :band_id,
    :dependent => :destroy
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :author_id, :body, :track_id

  belongs_to :track,
    :class_name => "Track",
    :primary_key => :id,
    :foreign_key => :track_id

  belongs_to :author,
    :class_name => "User",
    :primary_key => :id,
    :foreign_key => :author_id
end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :album_id, :name, :lyrics

  belongs_to :album,
    :class_name => "Album",
    :primary_key => :id,
    :foreign_key => :album_id

  has_one :band,
    :through => :album,
    :source => :band

  has_many :notes,
    :class_name => "Note",
    :primary_key => :id,
    :foreign_key => :track_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :token,
                  :activation_token, :activated, :admin

  has_many :notes,
    :class_name => "Note",
    :primary_key => :id,
    :foreign_key => :author_id
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @album = Album.new(params[:album])
    if @album.save
      redirect_to albums_url
    else
      flash[:notice] ||= []
      flash[:notice] << "Album couldn't be saved for some reason"
      redirect_to new_album_url
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to albums_url
  end

  def edit
    @album = Album.find(params[:id])
    @bands = Band.all
    render :edit
  end

  def index
    @albums = Album.all
    render :index
  end

  def new
    @bands = Band.all
    render :new
  end

  def show
    @album = Album.find(params[:id])
    @tracks = @album.tracks
    render :show
  end

  def update
    @album = Album.find(params[:id])
    @album.update_attributes(params[:album])
    redirect_to albums_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper

  def authenticate_user!
    redirect_to login_url unless logged_in?
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @band = Band.new(params[:band])
    if @band.save
      redirect_to bands_url
    else
      flash[:notices] ||= []
      flash[:notices] << "Band couldn't be saved for some reason"
      redirect_to new_band_url
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def index
    @bands = Band.all
    render :index
  end

  def new
    render :new
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def update
    @band = Band.find(params[:id])
    @band.update_attributes(params[:band])
    redirect_to bands_url
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :authenticate_user!

  def create
    @note = Note.new(params[:note])
    if @note.save
      redirect_to :back
    else
      flash[:notice] ||= []
      flash[:notice] << "note couldn't be saved for some reason"
      redirect_to :back
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to :back
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :login
  end

  def create
    @user = User.find_by_email(params[:user][:email])
    if @user && @user.password == params[:user][:password]
      login(@user)
      redirect_to bands_url
    else
      flash[:notice] ||= []
      flash[:notice] << "Login failed."
      redirect_to login_url
    end
  end

  def destroy
    logout
    redirect_to login_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_filter :authenticate_user!

  include TracksHelper

  def create
    @track = Track.new(params[:track])
    if @track.save
      redirect_to album_url(@track.album)
    else
      flash[:notice] ||= []
      flash[:notice] << "track couldn't be saved for some reason"
      redirect_to new_album_track_url(@track.album)
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to tracks_url
  end

  def edit
    @track = Track.find(params[:id])
    @album = @track.album
    render :edit
  end

  def new
    @album = Album.find(params[:album_id])
    @album_artist = @album.band
    render :new
  end

  def show
    @track = Track.find(params[:id])
    @lyrics = ugly_lyrics(@track.lyrics)
    @notes = @track.notes
    render :show
  end

  def update
    @track = Track.find(params[:id])
    @track.update_attributes(params[:track])

    @album = Album.find(params[:album_id])
    redirect_to album_track_url(@album, @track)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(params[:user])
    generate_activation_token
    if @user.save
      msg = UserMailer.welcome_email(@user)
      msg.deliver!

      flash[:notice] ||= []
      flash[:notice] << "Sign up successful!"

      redirect_to bands_url
    else
      flash[:notice] ||= []
      flash[:notice] << "Sign up failed. Try again!"

      redirect_to :back
    end
  end

  def activate
    @user = User.find_by_activation_token(params[:token])
    if @user
      @user.activated = true
      @user.save
      redirect_to bands_url
    else
      flash[:notice] ||= []
      flash[:notice] << "Activation failed."
      redirect_to login_url
    end
  end

  def generate_activation_token
    token = SecureRandom.urlsafe_base64
    while User.find_by_activation_token(token)
      token = SecureRandom.urlsafe_base64
    end
    @user.activation_token = token
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def generate_unique_random_token
    token = SecureRandom.urlsafe_base64
    while User.find_by_token(token)
      token = SecureRandom.urlsafe_base64
    end
    token
  end

  def login(user)
    user.token = generate_unique_random_token
    user.save!
    session[:token] = user.token
  end

  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_token(session[:token])
  end

  def logged_in?
    !!current_user
  end

  def logout
    session[:token] = nil
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
  def ugly_lyrics(lyrics)
    lines = lyrics.split("\n")

    lyrics = lines.map do |line|
      "&#9835; #{line}"
    end

    lyrics.join("\n").html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/edit.html.erb
<h1>Edit album</h1>

<form action="<%= albums_url %>" method="post">
  <label for="album_title">Title:</label>
  <input type=text name="album[title]" value="<%= @album.title %>">

  <select name="album[band_id]" id="album_artist">
    <% @bands.each do |band| %>
      <option value="<%= band.id %>"
        <%= "selected" if @album.band == band %>
      >
        <%= band.name %>
      </option>
    <% end %>

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="put">
  <input type="submit" value="Update album">
</form>

app/views/albums/index.html.erb
<h1>Albums</h1>

<table>
  <tr>
    <th>Title/Artist</th>
    <th></th>
    <th></th>
  </tr>

  <% @albums.each do |album| %>
    <tr>
      <td>
        <%= link_to "#{album.title}", album_url(album), :method => "get" %> <br />
        by <%= link_to "#{album.band.name}", band_url(album.band), :method => "get" %>
      </td>
      <td><%= link_to "edit", edit_album_url(album), :method => "get" %></td>

      <% if current_user.admin == true %>
      <td><%= link_to "delete", album_url(album), :method => "delete" %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<br />

<%= link_to "Create new album", new_album_url, :method => "get" %>

app/views/albums/new.html.erb
<h1>Create new album</h1>

<form action="<%= albums_url %>" method="post">
  <label for="album_title">Title:</label>
  <input type="text" name="album[title]">

  <select name="album[band_id]" id="album_artist">
    <% @bands.each do |band| %>
      <option value="<%= band.id %>">
        <%= band.name %>
      </option>
    <% end %>

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Submit">
</form>

app/views/albums/show.html.erb
<h1><%= @album.title %></h1>
<h3>Artist: <%= link_to "#{@album.band.name}", band_url(@album.band) %></h3>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>

  <% @tracks.each do |track| %>
    <tr>
      <td>
        <%= link_to "#{track.name}", album_track_url(@album, track), :method => "get" %>
      </td>
      <td><%= link_to "edit", edit_album_track_url(@album, track), :method => "get" %></td>

      <% if current_user.admin == true %>
      <td><%= link_to "delete", album_track_url(@album, track), :method => "delete" %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<br />

<%= link_to "Create new track", new_album_track_url(@album), :method => "get" %>

app/views/bands/edit.html.erb
<h1>Edit band</h1>

<form action="<%= band_url(@band) %>" method="post">
  <label for="band_name">Name:</label>
  <input type=text name="band[name]" value="<%= @band.name %>">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="put">
  <input type="submit" value="Update">
</form>

app/views/bands/index.html.erb
<h1>Bands</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>

  <% @bands.each do |band| %>
  <tr>
    <td><%= link_to "#{band.name}", band_url(band), :method => "get" %></td>
    <td><%= link_to "edit", edit_band_url(band), :method => "get" %></td>

    <% if current_user.admin == true %>
    <td><%= link_to "delete", band_url(band), :method => "delete" %></td>
    <% end %>
  </tr>
  <% end %>
</table>
<br />

<%= link_to "Create new band", new_band_url, :method => "get" %>

app/views/bands/new.html.erb
<h1>Create new band</h1>

<form action="<%= bands_url %>" method="post">
  <label for="band_name">Name:</label>
  <input type=text name="band[name]">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Submit">
</form>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<h3>Albums and Tracks</h3>

<ul>
  <% @band.albums.each do |album| %>
    <li>
    <%= link_to "#{album.title}", album_url(album) %> <br />
      <ul>
        <% album.tracks.each do |track| %>
          <%= link_to "#{track.name}", album_track_url(album, track) %> <br />
        <% end %>
      </ul>
    </li> <br />
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash[:notice].try(:each) do |msg| %>
  <%= msg %>
<% end %>

<% if current_user %>
  You are logged in as <%= current_user.email %>.
  <form action="<%= session_url %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <input type="submit" value="Logout">
  </form>
<% end %>

<%= yield %>
</body>
</html>

app/views/tracks/edit.html.erb
<h1>Edit track</h1>

<form action="<%= album_track_url(@album, @track) %>" method="post">
  <label for="track_name">Name:</label> <br />
  <input type="text" name="track[name]" value="<%= @track.name %>"> <br />

  <label for="track_lyrics">Lyrics:</label> <br />
  <textarea name="track[lyrics]"><%= @track.lyrics %></textarea> <br />

  <label for="track_album"><%= @track.band.name %> albums:</label> <br />
  <select name="track[album_id]" id="track_album">
    <% @album.band.albums.each do |album| %>
      <option value="<%= album.id %>"
        <%= "selected" if @album.id = album.id %>
      >
        <%= album.title %>
      </option>
    <% end %>
  </select> <br /> <br />

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="put">
  <input type="submit" value="Update">
</form>

app/views/tracks/index.html.erb
<h1>Tracks#index</h1>
<p>Find me in app/views/tracks/index.html.erb</p>

app/views/tracks/new.html.erb
<h1>Create new track</h1>

<form action="<%= album_tracks_url(@album) %>" method="post">
  <label for="track_name">Name:</label> <br />
  <input type="text" name="track[name]"> <br />

  <label for="track_lyrics">Lyrics:</label> <br />
  <textarea name="track[lyrics]"></textarea> <br />

  <label for="track_album"><%= @album_artist.name %> albums:</label> <br />
  <select name="track[album_id]" id="track_album">
    <% @album_artist.albums.each do |album| %>
      <option value="<%= album.id %>">
        <%= album.title %>
      </option>
    <% end %>
  </select> <br /> <br />

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Submit">
</form>

app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>
<%= link_to "Edit track", edit_album_track_url(@track.album, @track) %>

<h3>Artist: <%= link_to "#{@track.band.name}", band_url(@track.band) %></h3>
<h3>Album: <%= link_to "#{@track.album.title}", album_url(@track.album) %></h3>

<h3>Lyrics:</h3>
<pre><%= @lyrics %></pre>

<% if !@notes.empty? %>
  <h4>Notes:</h4>
  <ul>
    <% @notes.each do |note| %>
      <li>
        <%= note.body %>
        <% if note.author_id == current_user.id || current_user.admin == true %>
          <%= button_to "Delete", note_url(note), :method => :delete %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

<form action="<%= notes_url %>" method="post">
  Add note: <br />
  <textarea name="note[body]"></textarea> <br />

  <input type="hidden" name="note[track_id]" value="<%= @track.id %>">
  <input type="hidden" name="note[author_id]" value="<%= current_user.id %>">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Add note">
</form>

app/views/users/new.html.erb
<h1>Create new account</h1>

<form action="<%= users_url %>" method="post">
  Email: <input type="text" name="user[email]"> <br />
  Password: <input type="password" name="user[password]"> <br />

  <input type="hidden" name="user[activated]" value="false">

  <input type="submit" value="Sign up">
</form>